// ─── Domain: Maison Obsidian batch-atelier catalogue ─────────────────────────
//
// Seed catalogue: the original "Fragrance upload" sheet plus the 2026 audience
// sheet, which added 32 scents with an explicit Him / Her / Unisex audience and
// superseded four of the originals (Fiery Spice, Imperial Vintage, Fierce Amber
// and Shadowed Oud, each a different edition of a fragrance the new sheet
// carries). Prices are per size (10 / 30 / 50 ml) in cents; `price` is the 50 ml
// headline shown in the UI. Fields neither sheet provided:
//   • gender  — from the audience sheet's Him / Her / Unisex column; the
//     original 21 keep the reading assigned from their inspiration reference
//   • moq / committed — demo batch defaults
//   • liquid / accent — swatch colours derived from each scent's notes, by the
//     same lexicon the matching engine reads (lib/scentdna.ts)
//   • vipOnly — the single most expensive scent, so the VIP gate stays demoable

export type Gender = "masculine" | "feminine" | "unisex";

export interface Fragrance {
  id: string;
  slug: string;
  name: string;
  inspiration: string;
  tagline: string;
  story: string;
  price: number; // 50 ml, cents
  price10: number; // 10 ml, cents
  price30: number; // 30 ml, cents
  gender: Gender;
  moq: number;
  committed: number;
  liquid: string; // hex
  accent: string; // hex
  vipOnly?: boolean;
  top: string[];
  heart: string[];
  base: string[];
  // Inventory (on-hand stock per size). Optional: the seed omits it and the
  // admin/DB manage it; treat missing as 0 when displaying.
  stock10?: number;
  stock30?: number;
  stock50?: number;
  lowStock?: number;
  oilMl?: number; // raw oil on hand (ml), filled into bottles on demand
  // Presentation. `imageUrl` is a transparent PNG of the bottle: an admin
  // upload, else the house render at /assets/<slug>.png (see bottleImageFor),
  // else stock bottle photography. `profile` is the three-word scent
  // descriptor set by the AI conception, e.g. ["Dark", "Resinous", "Woody"].
  imageUrl?: string;
  profile?: string[];
  // Multi-format commerce. Per-fragrance price overrides (cents) and launch
  // status per format key; anything unset falls back to the house defaults in
  // formats.ts. Stock for the non-perfume formats lives alongside stock10/30/50.
  formatPrices?: Partial<Record<FormatKey, number>>;
  formatStatus?: Partial<Record<FormatKey, FormatStatus>>;
  stockCar?: number;
  stockWash?: number;
  stockMoist?: number;
}

export type FormatKey = "perf10" | "perf30" | "perf50" | "car" | "wash" | "moist" | "ritual";
export type FormatStatus = "live" | "coming_soon" | "hidden";

/**
 * The house bottle render for a fragrance: a transparent PNG named after its
 * slug in public/assets (e.g. /assets/smoky-obsidian.png). Used whenever no
 * admin-uploaded image is set; BottleImage falls back to stock photography if
 * the file is missing, so a new fragrance without a render still displays.
 */
export function bottleImageFor(slug: string): string {
  return `/assets/${slug}.png`;
}

/** Fills in the house bottle render for a fragrance that has no image set. */
export function withBottleImage<T extends Pick<Fragrance, "slug" | "imageUrl">>(f: T): T {
  return f.imageUrl ? f : { ...f, imageUrl: bottleImageFor(f.slug) };
}

const SEED: Fragrance[] = [
  {
    id: "f1",
    slug: "smoky-obsidian",
    name: "Smoky Obsidian",
    inspiration: "Inspired by Tom Ford - Black Lacquer",
    tagline: "Black Ink, Leather, Ebony Wood.",
    story: "Mysterious, avant-garde scent dominated by dark resins, rich ink accords, and warm, smoky woodiness.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 20,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Black Ink", "Rum"],
    heart: ["Leather", "Elemi Resin"],
    base: ["Ebony Wood", "Olibanum"],
    imageUrl: "/assets/Tom-Ford-Black-Lacquer-1.jpg",
  },
  {
    id: "f2",
    slug: "velvet-absolute",
    name: "Velvet Absolute",
    inspiration: "Inspired by YSL - MYSLF L'Absolu",
    tagline: "Bergamot, Orange Blossom, Amber.",
    story: "Modern, deeply sensual masculine scent blending rich ambery woods with an intense, clean floral core.",
    price: 4900,
    price10: 2100,
    price30: 3500,
    gender: "masculine",
    moq: 22,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Bergamot", "Black Pepper"],
    heart: ["Orange Blossom"],
    base: ["Amber", "Patchouli"],
    imageUrl: "/assets/YSL-MYSLF-L-Absolu-1.jpg",
  },
  {
    id: "f3",
    slug: "golden-aura",
    name: "Golden Aura",
    inspiration: "Inspired by Burberry - Goddess",
    tagline: "Vanilla Infusion, Vanilla Caviar, Vanilla Absolute.",
    story: "Luxurious, uniquely multi-dimensional vanilla fragrance elevated by clean lavender and rich earthy undertones.",
    price: 4900,
    price10: 2100,
    price30: 3500,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Vanilla Infusion", "Lavender"],
    heart: ["Vanilla Caviar"],
    base: ["Vanilla Absolute"],
    imageUrl: "/assets/Burberry%20Goddess.jpg",
  },
  {
    id: "f4",
    slug: "midnight-velvet",
    name: "Midnight Velvet",
    inspiration: "Inspired by YSL - Black Opium",
    tagline: "Pear, Coffee, Vanilla.",
    story: "Addictive, seductive gourmand blend balancing energizing dark coffee with sweet vanilla and white florals.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "feminine",
    moq: 30,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pear", "Pink Pepper"],
    heart: ["Coffee", "Jasmine"],
    base: ["Vanilla", "Patchouli", "Cedar"],
    imageUrl: "/assets/YSL%20%E2%80%94%20Black%20Opium.jpg",
  },
  {
    id: "f6",
    slug: "romance-vintage",
    name: "Romance Vintage",
    inspiration: "Inspired by YSL - Paris",
    tagline: "Rose, Violet, Iris.",
    story: "Timeless, romantic, and powdery floral masterpiece celebrating a classic, vibrant bouquet of roses and violets.",
    price: 4300,
    price10: 2000,
    price30: 3100,
    gender: "feminine",
    moq: 22,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Rose", "Mimosa"],
    heart: ["Violet", "Ylang-Ylang"],
    base: ["Iris", "Sandalwood", "Musk"],
    imageUrl: "/assets/YSL%20-%20Paris.jpg",
  },
  {
    id: "f7",
    slug: "floral-paradox",
    name: "Floral Paradox",
    inspiration: "Inspired by Prada - Prada Paradoxe",
    tagline: "Pear, Orange Blossom, Amber.",
    story: "Vibrant, multi-faceted floral scent capturing a fresh white bouquet reinvented with intense warmth and clean musk.",
    price: 4500,
    price10: 2100,
    price30: 3300,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pear", "Tangerine", "Bergamot"],
    heart: ["Orange Blossom", "Jasmine"],
    base: ["Amber", "White Musk"],
    imageUrl: "/assets/Prada%20Paradox.jpg",
  },
  {
    id: "f8",
    slug: "azure-edge",
    name: "Azure Edge",
    inspiration: "Inspired by YSL - Y EDP",
    tagline: "Apple, Sage, Amberwood.",
    story: "Bold, long-lasting fresh woody fragrance contrasting sharp, crisp clean notes with a deep amber base.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 30,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Apple", "Ginger", "Bergamot"],
    heart: ["Sage", "Juniper Berries"],
    base: ["Amberwood", "Tonka Bean"],
    imageUrl: "/assets/YSL%20%E2%80%94%20Y%20EDP.jpg",
  },
  {
    id: "f9",
    slug: "erosian-desire",
    name: "Erosian Desire",
    inspiration: "Inspired by Versace - Eros",
    tagline: "Mint, Tonka Bean, Vanilla.",
    story: "Vibrant, high-energy fresh oriental blend showcasing sweet mint, crisp green apple, and rich, warm tonka bean.",
    price: 4300,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 20,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Mint", "Green Apple", "Lemon"],
    heart: ["Tonka Bean", "Ambroxan"],
    base: ["Vanilla", "Cedarwood"],
    imageUrl: "/assets/Versace%20%E2%80%94%20Eros.jpg",
  },
  {
    id: "f10",
    slug: "sacred-smoke",
    name: "Sacred Smoke",
    inspiration: "Inspired by Tom Ford - Ebene Fume",
    tagline: "Palo Santo, Leather, Ebony Wood.",
    story: "Deeply meditative, spiritual woody scent centered around warm Palo Santo smoke, rich ebony, and luxurious resins.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "unisex",
    moq: 22,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Palo Santo", "Incense"],
    heart: ["Leather", "Labdanum"],
    base: ["Ebony Wood", "Guaiac Wood"],
    imageUrl: "/assets/Tom%20Ford%20-%20%20Ebene%20Fume.jpg",
  },
  {
    id: "f11",
    slug: "ethereal-drift",
    name: "Ethereal Drift",
    inspiration: "Inspired by Louis Vuitton - Imagination",
    tagline: "Citron, Nigerian Ginger, Chinese Black Tea.",
    story: "Ultra-refined, luminous fresh fragrance combining sparkling citrus fruits with rare black tea and warm ambroxan.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Citron", "Calabrian Bergamot"],
    heart: ["Nigerian Ginger", "Ceylon Cinnamon"],
    base: ["Chinese Black Tea", "Ambroxan"],
    imageUrl: "/assets/Lv%20Imagination.jpg",
  },
  {
    id: "f12",
    slug: "imperial-oud",
    name: "Imperial Oud",
    inspiration: "Inspired by Creed - Oud Zarian",
    tagline: "Saffron, Rose, Oud.",
    story: "Regal, sophisticated oriental woody blend pairing rich, smooth agarwood with warm spices and subtle leather.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 30,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Saffron", "Nutmeg"],
    heart: ["Rose", "Labdanum"],
    base: ["Oud", "Leather", "Amber"],
    imageUrl: "/assets/Creed%20Oud%20Zarain.jpg",
  },
  {
    id: "f13",
    slug: "marine-absolute",
    name: "Marine Absolute",
    inspiration: "Inspired by Giorgio Armani - Acqua Di Gio Absolu",
    tagline: "Marine Notes, Rosemary, Patchouli.",
    story: "Powerful marine fragrance where fresh sea water meets warm, elegant woods and rich patchouli.",
    price: 4200,
    price10: 2000,
    price30: 3000,
    gender: "masculine",
    moq: 20,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Marine Notes", "Bergamot"],
    heart: ["Rosemary", "Lavender"],
    base: ["Patchouli", "Warm Woods"],
    imageUrl: "/assets/Armani%20Acqua%20di%20Gio.jpg",
  },
  {
    id: "f14",
    slug: "wild-horizon",
    name: "Wild Horizon",
    inspiration: "Inspired by Dior - Sauvage EDP",
    tagline: "Calabria Bergamot, Sichuan Pepper, Ambroxan.",
    story: "Fiercely fresh, raw masculine composition balancing sharp bergamot with rich, smoky vanilla and heavy ambroxan.",
    price: 4000,
    price10: 1900,
    price30: 3000,
    gender: "masculine",
    moq: 22,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Calabria Bergamot"],
    heart: ["Sichuan Pepper", "Lavender"],
    base: ["Ambroxan", "Papua Vanilla"],
    imageUrl: "/assets/Dior%20Sauvage.jpg",
  },
  {
    id: "f16",
    slug: "neon-pulse",
    name: "Neon Pulse",
    inspiration: "Inspired by Jean Paul Gaultier - Ultra Male",
    tagline: "Pear, Cinnamon, Black Vanilla.",
    story: "Intensely sweet, high-impact masculine gourmand scent balancing spicy cinnamon with heavy black vanilla and juicy pear.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "masculine",
    moq: 30,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pear", "Lavender", "Mint"],
    heart: ["Cinnamon", "Clary Sage"],
    base: ["Black Vanilla", "Amber"],
    imageUrl: "/assets/JPG%20Ultra%20Male.jpg",
  },
  {
    id: "f17",
    slug: "dark-caramel",
    name: "Dark Caramel",
    inspiration: "Inspired by Azzaro - Most Wanted",
    tagline: "Cardamom, Toffee, Amberwood.",
    story: "Ultra-addictive, rich fiery fragrance combining spicy cardamom with warm toffee and a deep woody trail.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "masculine",
    moq: 20,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Cardamom"],
    heart: ["Toffee"],
    base: ["Amberwood"],
    imageUrl: "/assets/Azzaro%20%E2%80%94%20Most%20Wanted.jpg",
  },
  {
    id: "f18",
    slug: "noble-woods",
    name: "Noble Woods",
    inspiration: "Inspired by Creed - Spice & Wood",
    tagline: "Apple, Angelica, Cedarwood.",
    story: "Incredibly refined, aristocratic blend of crisp green apple, sharp aromatic spices, and a clean, precious wood base.",
    price: 3800,
    price10: 1900,
    price30: 2800,
    gender: "unisex",
    moq: 22,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Apple", "Bergamot", "Lemon"],
    heart: ["Angelica", "Clove", "Pepper"],
    base: ["Cedarwood", "Birch", "Iris"],
    imageUrl: "/assets/Creed%20%E2%80%94%20Spice%20and%20Wood.jpg",
  },
  {
    id: "f19",
    slug: "golden-elixir",
    name: "Golden Elixir",
    inspiration: "Inspired by Jean Paul Gaultier - Le Male Elixir",
    tagline: "Lavender, Vanilla, Honey.",
    story: "Rich, deeply aromatic oriental blend featuring intensely warm honeyed tobacco, clean lavender, and sweet tonka bean.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Lavender", "Mint"],
    heart: ["Vanilla", "Benzoin"],
    base: ["Honey", "Tobacco", "Tonka Bean"],
    imageUrl: "/assets/Jean%20Paul%20Gaultier%20%E2%80%94%20Le%20Male%20Elixir.jpg",
  },
  {
    id: "f21",
    slug: "smoked-suede",
    name: "Smoked Suede",
    inspiration: "Inspired by Tom Ford - Tuscan Leather",
    tagline: "Raspberry, Olibanum, Leather.",
    story: "Bold, ultra-luxurious lifestyle scent combining raw, heavy dark leather with sweet, bright wild raspberries.",
    price: 4000,
    price10: 1900,
    price30: 3000,
    gender: "unisex",
    moq: 20,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Raspberry", "Saffron"],
    heart: ["Olibanum", "Jasmine"],
    base: ["Leather", "Suede", "Amberwood"],
    imageUrl: "/assets/Tom%20Ford%20%E2%80%94%20Tuscan%20Leather.jpg",
  },
  {
    id: "f22",
    slug: "dark-prestige",
    name: "Dark Prestige",
    inspiration: "Inspired by BOSS Bottle Absolu",
    tagline: "Leather Accord, Patchouli, Davana.",
    story: "Deeply intense, roasted woody-amber composition featuring rich leather accords, warm patchouli, and deep cedar.",
    price: 3600,
    price10: 1800,
    price30: 2700,
    gender: "masculine",
    moq: 22,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Leather Accord"],
    heart: ["Patchouli", "Cedarwood"],
    base: ["Davana", "Labdanum"],
    imageUrl: "/assets/BOSS%20Bottle%20Absolu.jpg",
  },
  {
    id: "f24",
    slug: "celestial-fields",
    name: "Celestial Fields",
    inspiration: "Inspired by Roja - Elysium Eau",
    tagline: "Grapefruit, Lily-of-the-Valley, Ambergris.",
    story: "Brilliantly bright, sophisticated fresh fragrance bursting with crisp citrus, green apple, and clean, elegant musk.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 30,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Grapefruit", "Bergamot", "Lime"],
    heart: ["Lily-of-the-Valley", "Jasmine", "Apple"],
    base: ["Ambergris", "Musk", "Leather"],
    imageUrl: "/assets/Roja-Elysium-Eau-1.jpg",
  },
  {
    id: "f25",
    slug: "desert-nomad",
    name: "Desert Nomad",
    inspiration: "Inspired by Tom Ford - Ombre Nomade",
    tagline: "Raspberry, Saffron, Oud.",
    story: "Masterful, high-impact oriental fragrance combining deeply smoky oud wood with rich leather and sweet, dark raspberry.",
    price: 6300,
    price10: 2500,
    price30: 4400,
    gender: "unisex",
    moq: 20,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    vipOnly: true,
    top: ["Raspberry"],
    heart: ["Saffron", "Rose"],
    base: ["Oud", "Leather", "Incense"],
    imageUrl: "/assets/Tom-Ford-Ombre-Nomade-1.jpg",
  },
  {
    id: "f26",
    slug: "ventus",
    name: "Ventus",
    inspiration: "Inspired by Creed - Aventus",
    tagline: "Pineapple & Blackcurrant, Birch, Musk.",
    story: "Bold, sophisticated, and masculine scent that balances fresh fruitiness with a deep, smoky, and woody dry-down.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pineapple & Blackcurrant", "Apple", "Bergamot"],
    heart: ["Birch", "Patchouli", "Moroccan Jasmine & Rose"],
    base: ["Musk", "Oakmoss", "Ambergris", "Vanilla"],
    imageUrl: "/assets/Creed%20Aventus%20Absolu.jpg",
  },
  {
    id: "f27",
    slug: "mariners-odyssey",
    name: "Mariner's Odyssey",
    inspiration: "Inspired by Amouage - Sindbad",
    tagline: "Cardamom, Frankincense, Oud.",
    story: "An adventurous and opulent oriental woody fragrance blending rich spices, aromatic resins, and deep oceanic amber woods.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Cardamom", "Cinnamon", "Bergamot", "Saffron"],
    heart: ["Frankincense", "Myrrh", "Rose", "Osmanthus"],
    base: ["Oud", "Sandalwood", "Amber", "Leather"],
    imageUrl: "/assets/amouage%20sindbad.jpg",
  },
  {
    id: "f28",
    slug: "london-berry-blossom",
    name: "London Berry Blossom",
    inspiration: "Inspired by Burberry - Her",
    tagline: "Strawberry, Violet, Musk.",
    story: "A vibrant, fruity-floral gourmand scent bursting with luscious red berries, jasmine, and a warm, powdery musk base.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Strawberry", "Raspberry", "Blackberry", "Sour Cherry", "Black Currant", "Mandarin Orange", "Lemon"],
    heart: ["Violet", "Jasmine"],
    base: ["Musk", "Vanilla", "Cashmeran", "Woody Notes", "Amber", "Oakmoss"],
    imageUrl: "/assets/Burberry-Her-1.jpg",
  },
  {
    id: "f29",
    slug: "midnight-berry-noir",
    name: "Midnight Berry Noir",
    inspiration: "Inspired by Burberry - Her Intense",
    tagline: "Blackberry, Jasmine, Benzoin.",
    story: "A richer, bolder, and more seductive interpretation of the original, dominated by dark blackberry, jasmine, and warm benzoin.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Blackberry", "Red Fruits"],
    heart: ["Jasmine"],
    base: ["Benzoin"],
  },
  {
    id: "f30",
    slug: "obsidian-gentleman",
    name: "Obsidian Gentleman",
    inspiration: "Inspired by Bvlgari - Man In Black",
    tagline: "Spices, Leather, Tonka Bean.",
    story: "A charismatic amber floral fragrance featuring bold rum, intoxicating spices, tuberose, leather, and rich tonka bean.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Spices", "Rum", "Tobacco"],
    heart: ["Leather", "Iris", "Tuberose"],
    base: ["Tonka Bean", "Guaiac Wood", "Benzoin"],
    imageUrl: "/assets/Bvlgari-Man-In-Black-1.jpg",
  },
  {
    id: "f31",
    slug: "mademoiselle-elegance",
    name: "Mademoiselle Elegance",
    inspiration: "Inspired by Chanel - Coco Mademoiselle",
    tagline: "Orange, Turkish Rose, Patchouli.",
    story: "A timeless and alluring amber floral scent combining sparkling citrus with delicate rose, jasmine, patchouli, and sweet vanilla.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Orange", "Mandarin Orange", "Bergamot", "Orange Blossom"],
    heart: ["Turkish Rose", "Jasmine", "Mimosa", "Ylang-Ylang"],
    base: ["Patchouli", "White Musk", "Vanilla", "Vetiver", "Tonka Bean", "Opoponax"],
    imageUrl: "/assets/Coco-Chanel-Mademoiselle-1.jpg",
  },
  {
    id: "f32",
    slug: "midnight-addiction",
    name: "Midnight Addiction",
    inspiration: "Inspired by Dior - Addict",
    tagline: "Silk Tree Blossom, Night Blooming Cereus, Bourbon Vanilla.",
    story: "A captivating and intensely sensual floral oriental fragrance dominated by silky night-blooming cereus, mandarin leaf, and warm bourbon vanilla.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Silk Tree Blossom", "Mandarin Leaf"],
    heart: ["Night Blooming Cereus", "Orange Blossom"],
    base: ["Bourbon Vanilla", "Tonka Bean", "Sandalwood"],
    imageUrl: "/assets/Dior-Addict-1.jpg",
  },
  {
    id: "f33",
    slug: "golden-blossom",
    name: "Golden Blossom",
    inspiration: "Inspired by Dior - J'Adore",
    tagline: "Magnolia, Tuberose, Musk.",
    story: "A radiant and sophisticated floral bouquet celebrating ylang-ylang, Damask rose, and precious jasmine notes.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Magnolia", "Melon", "Peach", "Pear", "Bergamot", "Mandarin Orange"],
    heart: ["Tuberose", "Plum", "Violet", "Orchid", "Freesia", "Jasmine", "Lily-of-the-Valley", "Rose"],
    base: ["Musk", "Vanilla", "Cedar", "Blackberry"],
    imageUrl: "/assets/Dior-J-Adore-1.jpg",
  },
  {
    id: "f34",
    slug: "infinite-devotion",
    name: "Infinite Devotion",
    inspiration: "Inspired by Giorgio Armani - Stronger With You Intensely",
    tagline: "Pink Pepper, Toffee, Vanilla.",
    story: "An addictive and warm fougère fragrance blending pink pepper, lavender, and a rich, sweet heart of chestnut and vanilla.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pink Pepper", "Juniper", "Violet"],
    heart: ["Toffee", "Cinnamon", "Lavender", "Sage"],
    base: ["Vanilla", "Tonka Bean", "Amber", "Suede"],
    imageUrl: "/assets/Giorgio-Armani-Stronger-With-You-Intensely-1.jpg",
  },
  {
    id: "f35",
    slug: "ginger-ribbon",
    name: "Ginger Ribbon",
    inspiration: "Inspired by Hermès - Twilly d'Hermès",
    tagline: "Ginger, Tuberose, Sandalwood.",
    story: "A spirited and daring floral fragrance driven by zesty ginger, tuberose, and warm sandalwood.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Ginger", "Bitter Orange", "Bergamot"],
    heart: ["Tuberose", "Orange Blossom", "Jasmine"],
    base: ["Sandalwood", "Vanilla"],
    imageUrl: "/assets/Herm-s-Twilly-d-Herm-s-1.jpg",
  },
  {
    id: "f36",
    slug: "cascade-pure",
    name: "Cascade Pure",
    inspiration: "Inspired by Issey Miyake - Eau D'Issey",
    tagline: "Lotus, Lily-of-the-Valley, Musk.",
    story: "A clean, aquatic, and transparent floral fragrance evoking fresh spring water mixed with delicate lotus, rose, and precious woods.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Lotus", "Melon", "Calone", "Rose", "Freesia", "Lotus", "Cyclamen"],
    heart: ["Lily-of-the-Valley", "Water Peony", "Carnation", "Fresh Lily"],
    base: ["Musk", "Tuberose", "Exotic Woods", "Osmanthus", "Cedar", "Sandalwood", "Amber"],
    imageUrl: "/assets/Issey-Miyake-Eau-D-Issey-1.jpg",
  },
  {
    id: "f37",
    slug: "aura-crystal",
    name: "Aura Crystal",
    inspiration: "Inspired by Maison Francis Kurkdjian - Baccarat Rouge 540",
    tagline: "Saffron, Amberwood, Fir Resin.",
    story: "A luminous and ultra-sophisticated amber floral woody scent featuring airy jasmine, radiant saffron, cedarwood, and warm ambergris.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Saffron", "Jasmine"],
    heart: ["Amberwood", "Ambergris"],
    base: ["Fir Resin", "Cedar"],
    imageUrl: "/assets/Baccarat-Rouge-540-1.jpg",
  },
  {
    id: "f38",
    slug: "savanna-nomad",
    name: "Savanna Nomad",
    inspiration: "Inspired by Memo Paris - African Leather",
    tagline: "Cardamom, Geranium, Leather.",
    story: "An exotic and leathery spicy fragrance inspired by wild safari journeys, blending cardamom, saffron, cumin, patchouli, and rich leather.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Cardamom", "Saffron", "Cumin", "Bergamot"],
    heart: ["Geranium", "Patchouli", "Oud"],
    base: ["Leather", "Cumin", "Vetiver", "Musk", "Oud"],
    imageUrl: "/assets/Memo-Paris-African-Leather-1.jpg",
  },
  {
    id: "f39",
    slug: "velvet-musk-noir",
    name: "Velvet Musk Noir",
    inspiration: "Inspired by Narciso Rodriguez - For Her",
    tagline: "African Orange Flower, Musk, Vetiver.",
    story: "A magnetic and intimate musky floral chypre featuring honeyed orange blossom, osmanthus, amber, and rich patchouli.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["African Orange Flower", "Osmanthus", "Bergamot"],
    heart: ["Musk", "Amber"],
    base: ["Vetiver", "Vanille", "Patchouli"],
    imageUrl: "/assets/Narciso-Rodriguez-For-Her-1.jpg",
  },
  {
    id: "f40",
    slug: "golden-vanilla-royale",
    name: "Golden Vanilla Royale",
    inspiration: "Inspired by Parfums de Marly - Althaïr",
    tagline: "Cinnamon, Bourbon Vanilla, Praline.",
    story: "A decadent and creamy amber vanilla fragrance highlighting warm cinnamon, orange blossom, Bourbon vanilla, and praline.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Cinnamon", "Cardamom", "Orange Blossom", "Bergamot"],
    heart: ["Bourbon Vanilla", "Elemi"],
    base: ["Praline", "Musk", "Ambroxan", "Guaiac Wood"],
    imageUrl: "/assets/Parfums-de-Marly-Altha-r-1.jpg",
  },
  {
    id: "f41",
    slug: "royal-damask-rose",
    name: "Royal Damask Rose",
    inspiration: "Inspired by Parfums de Marly - Delina Exclusif",
    tagline: "Pear, Turkish Rose, Vanilla.",
    story: "An opulent, powdery floral masterpiece centered around luscious Turkish rose, pear, incense, and a creamy vanilla-musk base.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Pear", "Bergamot", "Litchi"],
    heart: ["Turkish Rose", "Oud", "Incense"],
    base: ["Vanilla", "Amber", "Woody Notes"],
    imageUrl: "/assets/Parfums-de-Marly-Delina-Exclusif-1.jpg",
  },
  {
    id: "f42",
    slug: "majestic-arabian-oud",
    name: "Majestic Arabian Oud",
    inspiration: "Inspired by The Spirit of Dubai - Oud",
    tagline: "Spices, Oud, Amber.",
    story: "A majestic and deeply resinous oriental woody fragrance featuring rich natural oud, spices, rose, leather, and precious amber.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Spices", "Fruity Notes", "Pine", "Cypriol Oil", "Lavender", "Bergamot", "Saffron"],
    heart: ["Oud", "Agarwood", "Amber", "Patchouli", "Caramel", "Myrrh", "Incense", "Rose", "Floral Notes"],
    base: ["Oud", "Amber", "Leather", "Tobacco", "Cedar", "Musk", "Sandalwood", "Vetiver"],
    imageUrl: "/assets/The-Spirit-of-Dubai-Oud-1.jpg",
  },
  {
    id: "f43",
    slug: "smoky-timber",
    name: "Smoky Timber",
    inspiration: "Inspired by Tom Ford - Oud Wood",
    tagline: "Rosewood, Oud Wood, Tonka Bean.",
    story: "A luxurious and smoky woody fragrance pairing rare oud wood with exotic rosewood, cardamom, tonka bean, and amber.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Rosewood", "Cardamom", "Chinese Pepper"],
    heart: ["Oud Wood", "Sandalwood", "Vetiver"],
    base: ["Tonka Bean", "Vanilla", "Amber"],
    imageUrl: "/assets/Tom-Ford-Oud-Wood-1.jpg",
  },
  {
    id: "f44",
    slug: "solar-amber-breeze",
    name: "Solar Amber Breeze",
    inspiration: "Inspired by Tom Ford - Soleil Blanc",
    tagline: "Pistachio, Tuberose, Coconut.",
    story: "A solar, amber-floral coco-infused fragrance evoking sun-drenched private islands with coconut, white florals, and amber.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pistachio", "Bergamot", "Cardamom", "Pink Pepper"],
    heart: ["Tuberose", "Ylang-Ylang", "Jasmine"],
    base: ["Coconut", "Amber", "Tonka Bean", "Benzoin"],
    imageUrl: "/assets/Tom-Ford-Soleil-Blanc-1.jpg",
  },
  {
    id: "f45",
    slug: "roman-sunrise",
    name: "Roman Sunrise",
    inspiration: "Inspired by Valentino - Donna Born In Roma",
    tagline: "Black Currant, Jasmine, Bourbon Vanilla.",
    story: "A modern couture floral floriental scent combining vibrant blackcurrant, jasmine, pink pepper, and rich bourbon vanilla.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Black Currant", "Pink Pepper", "Bergamot"],
    heart: ["Jasmine", "Jasmine Sambac", "Jasmine Tea"],
    base: ["Bourbon Vanilla", "Cashmeran", "Guaiac Wood"],
    imageUrl: "/assets/Valentino-Donna-Born-In-Roma-1.jpg",
  },
  {
    id: "f46",
    slug: "floral-explosion",
    name: "Floral Explosion",
    inspiration: "Inspired by Viktor&Rolf - Flowerbomb",
    tagline: "Tea, Orchid, Patchouli.",
    story: "An explosive bouquet of sweet and opulent floral notes featuring tea, bergamot, freesia, jasmine, orchid, and patchouli.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Tea", "Bergamot", "Osmanthus"],
    heart: ["Orchid", "Jasmine", "Rose", "Freesia", "African Orange Flower"],
    base: ["Patchouli", "Musk", "Vanilla"],
    imageUrl: "/assets/Viktor-Rolf-Flowerbomb-1.jpg",
  },
  {
    id: "f47",
    slug: "midnight-spice-noir",
    name: "Midnight Spice Noir",
    inspiration: "Inspired by Viktor&Rolf - Spicebomb Dark Leather",
    tagline: "Black Pepper, Cinnamon, Tobacco.",
    story: "An intense and rebellious leather and spice creation blending dark black pepper, nutmeg, cinnamon, leather, and tobacco.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Black Pepper", "Nutmeg"],
    heart: ["Cinnamon", "Leather", "Saffron"],
    base: ["Tobacco", "Dark Wood", "Cedar"],
    imageUrl: "/assets/Viktor-Rolf-Spicebomb-Dark-Leather-1.jpg",
  },
  {
    id: "f48",
    slug: "freesia-horizon",
    name: "Freesia Horizon",
    inspiration: "Inspired by YSL - Libre",
    tagline: "Mandarin Orange, Jasmine, Madagascar Vanilla.",
    story: "A bold and freedom-loving floral lavender fragrance featuring French lavender, Moroccan orange blossom, and warm golden ambergris.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Mandarin Orange", "Lavender", "Black Currant", "Petitgrain"],
    heart: ["Jasmine", "Lavender", "Orange Blossom"],
    base: ["Madagascar Vanilla", "Musk", "Cedar", "Ambergris"],
    imageUrl: "/assets/YSL-Libre-1.jpg",
  },
  {
    id: "f49",
    slug: "velvet-vanilla-indulgence",
    name: "Velvet Vanilla Indulgence",
    inspiration: "Inspired by Tom Ford - Vanilla Sex",
    tagline: "Bitter Almond, Vanilla Absolute, Tonka Bean.",
    story: "A decadent, sensual amber-vanilla fragrance blending distinctive Indian vanilla tincture, creamy sandalwood, and warm floral undertones.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Bitter Almond", "Clary Sage"],
    heart: ["Vanilla Absolute", "Floral Notes", "Orris"],
    base: ["Tonka Bean", "Vanilla Tincture", "Sandalwood", "Leather"],
    imageUrl: "/assets/Tom-Ford-Vanilla-Sex-1.jpg",
  },
  {
    id: "f50",
    slug: "crimson-leather-femme",
    name: "Crimson Leather Femme",
    inspiration: "Inspired by Gucci - Guilty Absolute Pour Femme",
    tagline: "Blackberry, Bulgarian Rose, Amber.",
    story: "A rich, woody-chypre fragrance highlighting dark blackberry, golden wood, bulgarian rose, and mysterious patchouli.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Blackberry", "Bergamot", "Pink Pepper"],
    heart: ["Bulgarian Rose", "Woody Notes", "Cypress", "Vetiver"],
    base: ["Amber", "Patchouli"],
    imageUrl: "/assets/Gucci-Guilty-Absolute-Pour-Femme-1.jpg",
  },
  {
    id: "f51",
    slug: "solar-lotus-radiance",
    name: "Solar Lotus Radiance",
    inspiration: "Inspired by Issey Miyake - L'Eau d'Issey Lumière",
    tagline: "Lotus, White Flowers, Cedar.",
    story: "A luminous and airy floral aquatic scent capturing morning dew, delicate lotus, freesia, and precious woods.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Lotus", "Freesia", "Lemon"],
    heart: ["White Flowers", "Ylang-Ylang", "Tuberose", "Rose"],
    base: ["Cedar", "Sandalwood", "Musk"],
    imageUrl: "/assets/Issey-Miyake-L-Eau-d-Issey-Lumi-re-1.jpg",
  },
  {
    id: "f52",
    slug: "chloe-chiffon-rose",
    name: "Chloé Chiffon Rose",
    inspiration: "Inspired by Chloé - Eau de Parfum",
    tagline: "Peony, Rose, Amber.",
    story: "A classic, elegant, and breezy floral powdery rose fragrance paired with magnolia, lily-of-the-valley, and warm amber.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Peony", "Litchi", "Freesia"],
    heart: ["Rose", "Lily-of-the-Valley", "Magnolia"],
    base: ["Amber", "Virginia Cedar"],
    imageUrl: "/assets/Chlo-Eau-de-Parfum-1.jpg",
  },
  {
    id: "f53",
    slug: "electric-night-vip",
    name: "Electric Night VIP",
    inspiration: "Inspired by Carolina Herrera - 212 VIP Black",
    tagline: "Absinthe, Lavender, Musk.",
    story: "A bold, energetic aromatic fougère fragrance blending absinthe, anise, lavender, and rich dark vanilla-musk.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Absinthe", "Anise", "Fennel"],
    heart: ["Lavender"],
    base: ["Musk", "Vanilla Husk"],
    imageUrl: "/assets/212%20VIP%20BLACK%20ELIXIR.jpg",
  },
  {
    id: "f54",
    slug: "amber-leather-scent",
    name: "Amber Leather Scent",
    inspiration: "Inspired by Hugo Boss - The Scent",
    tagline: "Peach, Osmanthus, Roasted Cocoa.",
    story: "A magnetic and seductive fragrance featuring honeyed peach, exotic freesia, toasted roasted cocoa, and rich leather.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "masculine",
    moq: 25,
    committed: 0,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Peach", "Freesia"],
    heart: ["Osmanthus"],
    base: ["Roasted Cocoa", "Leather Notes"],
    imageUrl: "/assets/Hugo-Boss-The-Scent-1.jpg",
  },
  {
    id: "f55",
    slug: "citrus-oceanic-splash",
    name: "Citrus Oceanic Splash",
    inspiration: "Inspired by Louis Vuitton - Afternoon Swim",
    tagline: "Sicilian Orange, Ginger, Ambergris.",
    story: "A vibrant, uplifting citrus aquatic fragrance bursting with sun-drenched Sicilian orange, bergamot, and crisp mandarin.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 25,
    committed: 0,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Sicilian Orange", "Bergamot", "Mandarin Orange"],
    heart: ["Ginger", "Sea Notes"],
    base: ["Ambergris", "Ambroxan"],
    imageUrl: "/assets/Louis-Vuitton-Afternoon-Swim-1.jpg",
  },
  {
    id: "f56",
    slug: "mediterranean-sunlit-citrus",
    name: "Mediterranean Sunlit Citrus",
    inspiration: "Inspired by Roberto Cavalli - Paradiso",
    tagline: "Citrus, Jasmine, Pine.",
    story: "A radiant, sun-soaked woody floral fragrance celebrating sparkling citrus, jasmine, pine, and warm cypress.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Citrus", "Mandarin Orange", "Bergamot"],
    heart: ["Jasmine"],
    base: ["Pine", "Cypress", "Laurel", "Parasol Pine", "White Nerium Oleander"],
    imageUrl: "/assets/Roberto-Cavalli-Paradiso-1.jpg",
  },
  {
    id: "f57",
    slug: "weekend-blossom-breeze",
    name: "Weekend Blossom Breeze",
    inspiration: "Inspired by Burberry - Weekend For Women",
    tagline: "Mignonette, Nectarine, Sandalwood.",
    story: "A relaxed, sparkling floral fragrance combining zesty tangerine, reseda plant, wild rose, peach blossom, and cedar.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "feminine",
    moq: 25,
    committed: 0,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Mignonette", "Mandarin Orange", "Sage"],
    heart: ["Nectarine", "Blue Hyacinth", "Peach Blossom", "Rose", "Iris", "Red Cyclamen"],
    base: ["Sandalwood", "Cedar", "Musk"],
    imageUrl: "/assets/Burberry-Weekend-For-Women-1.jpg",
  },
];

export const FRAGS: Fragrance[] = SEED.map(withBottleImage);

// ─── Design tokens ───────────────────────────────────────────────────────────
export const GOLD = "#c9a961";
export const CREAM = "#f3ecdc";
export const OBSIDIAN = "#0b0b0d";
export const HAIRLINE = "#1f1f27";

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Lighten (p > 0) or darken (p < 0) a #rrggbb hex toward white/black. */
export function shade(hex: string, p: number): string {
  const n = parseInt(hex.slice(1), 16);
  let r = (n >> 16) & 255;
  let g = (n >> 8) & 255;
  let b = n & 255;
  const t = p < 0 ? 0 : 255;
  const a = Math.abs(p);
  r = Math.round(r + (t - r) * a);
  g = Math.round(g + (t - g) * a);
  b = Math.round(b + (t - b) * a);
  return `rgb(${r},${g},${b})`;
}

export function money(cents: number): string {
  return "$" + Math.round(cents / 100);
}

/**
 * Money with the cents kept when they matter. Shelf prices are whole dollars,
 * but postage rarely is, and rounding a charge is how you lose trust.
 */
export function moneyExact(cents: number): string {
  return cents % 100 === 0 ? `$${cents / 100}` : `$${(cents / 100).toFixed(2)}`;
}

export function pad(n: number): string {
  return String(n).padStart(2, "0");
}

export type Filter = "all" | "men" | "women";

export function matches(f: Fragrance, filter: Filter): boolean {
  if (filter === "all") return true;
  if (filter === "men") return f.gender === "masculine" || f.gender === "unisex";
  return f.gender === "feminine" || f.gender === "unisex";
}
