// ─── Domain: Maison Obsidian batch-atelier catalogue ─────────────────────────
//
// Seed catalogue generated from the "Fragrance upload" spreadsheet. Prices are
// per size (10 / 30 / 50 ml) in cents; `price` is the 50 ml headline shown in the
// UI. Fields the sheet did not provide are documented in the README:
//   • gender  — assigned from the inspiration reference (sheet omitted it)
//   • moq / committed — demo batch defaults
//   • liquid / accent — swatch colours derived from each scent's notes
//   • vipOnly — the single most expensive scent, so the VIP gate stays demoable

export type Gender = "masculine" | "feminine" | "unisex";

export interface Fragrance {
  id: string;
  slug: string;
  name: string;
  inspiration: string;
  tagline: string;
  story: string;
  price: number; // 50 ml, cents
  price10: number; // 10 ml, cents
  price30: number; // 30 ml, cents
  gender: Gender;
  moq: number;
  committed: number;
  liquid: string; // hex
  accent: string; // hex
  vipOnly?: boolean;
  top: string[];
  heart: string[];
  base: string[];
}

export const FRAGS: Fragrance[] = [
  {
    id: "f1",
    slug: "smoky-obsidian",
    name: "Smoky Obsidian",
    inspiration: "Inspired by Tom Ford - Black Lacquer",
    tagline: "Black Ink, Leather, Ebony Wood.",
    story: "Mysterious, avant-garde scent dominated by dark resins, rich ink accords, and warm, smoky woodiness.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 20,
    committed: 3,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Black Ink", "Rum"],
    heart: ["Leather", "Elemi Resin"],
    base: ["Ebony Wood", "Olibanum"],
  },
  {
    id: "f2",
    slug: "velvet-absolute",
    name: "Velvet Absolute",
    inspiration: "Inspired by YSL - MYSLF L'Absolu",
    tagline: "Bergamot, Orange Blossom, Amber.",
    story: "Modern, deeply sensual masculine scent blending rich ambery woods with an intense, clean floral core.",
    price: 4900,
    price10: 2100,
    price30: 3500,
    gender: "masculine",
    moq: 22,
    committed: 10,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Bergamot", "Black Pepper"],
    heart: ["Orange Blossom"],
    base: ["Amber", "Patchouli"],
  },
  {
    id: "f3",
    slug: "golden-aura",
    name: "Golden Aura",
    inspiration: "Inspired by Burberry - Goddess",
    tagline: "Vanilla Infusion, Vanilla Caviar, Vanilla Absolute.",
    story: "Luxurious, uniquely multi-dimensional vanilla fragrance elevated by clean lavender and rich earthy undertones.",
    price: 4900,
    price10: 2100,
    price30: 3500,
    gender: "feminine",
    moq: 25,
    committed: 17,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Vanilla Infusion", "Lavender"],
    heart: ["Vanilla Caviar"],
    base: ["Vanilla Absolute"],
  },
  {
    id: "f4",
    slug: "midnight-velvet",
    name: "Midnight Velvet",
    inspiration: "Inspired by YSL - Black Opium",
    tagline: "Pear, Coffee, Vanilla.",
    story: "Addictive, seductive gourmand blend balancing energizing dark coffee with sweet vanilla and white florals.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "feminine",
    moq: 30,
    committed: 24,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pear", "Pink Pepper"],
    heart: ["Coffee", "Jasmine"],
    base: ["Vanilla", "Patchouli", "Cedar"],
  },
  {
    id: "f5",
    slug: "fiery-spice",
    name: "Fiery Spice",
    inspiration: "Inspired by Viktor&Rolf - Spicebomb Extreme",
    tagline: "Black Pepper, Cinnamon, Tobacco.",
    story: "Explosive, deeply warming oriental blend of heavy spices, rich tobacco, and a sweet, creamy vanilla dry-down.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 20,
    committed: 10,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Black Pepper", "Pimento"],
    heart: ["Cinnamon", "Cumin"],
    base: ["Tobacco", "Vanilla"],
  },
  {
    id: "f6",
    slug: "romance-vintage",
    name: "Romance Vintage",
    inspiration: "Inspired by YSL - Paris",
    tagline: "Rose, Violet, Iris.",
    story: "Timeless, romantic, and powdery floral masterpiece celebrating a classic, vibrant bouquet of roses and violets.",
    price: 4300,
    price10: 2000,
    price30: 3100,
    gender: "feminine",
    moq: 22,
    committed: 15,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Rose", "Mimosa"],
    heart: ["Violet", "Ylang-Ylang"],
    base: ["Iris", "Sandalwood", "Musk"],
  },
  {
    id: "f7",
    slug: "floral-paradox",
    name: "Floral Paradox",
    inspiration: "Inspired by Prada - Prada Paradoxe",
    tagline: "Pear, Orange Blossom, Amber.",
    story: "Vibrant, multi-faceted floral scent capturing a fresh white bouquet reinvented with intense warmth and clean musk.",
    price: 4500,
    price10: 2100,
    price30: 3300,
    gender: "feminine",
    moq: 25,
    committed: 19,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pear", "Tangerine", "Bergamot"],
    heart: ["Orange Blossom", "Jasmine"],
    base: ["Amber", "White Musk"],
  },
  {
    id: "f8",
    slug: "azure-edge",
    name: "Azure Edge",
    inspiration: "Inspired by YSL - Y EDP",
    tagline: "Apple, Sage, Amberwood.",
    story: "Bold, long-lasting fresh woody fragrance contrasting sharp, crisp clean notes with a deep amber base.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 30,
    committed: 21,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Apple", "Ginger", "Bergamot"],
    heart: ["Sage", "Juniper Berries"],
    base: ["Amberwood", "Tonka Bean"],
  },
  {
    id: "f9",
    slug: "erosian-desire",
    name: "Erosian Desire",
    inspiration: "Inspired by Versace - Eros",
    tagline: "Mint, Tonka Bean, Vanilla.",
    story: "Vibrant, high-energy fresh oriental blend showcasing sweet mint, crisp green apple, and rich, warm tonka bean.",
    price: 4300,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 20,
    committed: 17,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Mint", "Green Apple", "Lemon"],
    heart: ["Tonka Bean", "Ambroxan"],
    base: ["Vanilla", "Cedarwood"],
  },
  {
    id: "f10",
    slug: "sacred-smoke",
    name: "Sacred Smoke",
    inspiration: "Inspired by Tom Ford - Ebene Fume",
    tagline: "Palo Santo, Leather, Ebony Wood.",
    story: "Deeply meditative, spiritual woody scent centered around warm Palo Santo smoke, rich ebony, and luxurious resins.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "unisex",
    moq: 22,
    committed: 20,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Palo Santo", "Incense"],
    heart: ["Leather", "Labdanum"],
    base: ["Ebony Wood", "Guaiac Wood"],
  },
  {
    id: "f11",
    slug: "ethereal-drift",
    name: "Ethereal Drift",
    inspiration: "Inspired by Louis Vuitton - Imagination",
    tagline: "Citron, Nigerian Ginger, Chinese Black Tea.",
    story: "Ultra-refined, luminous fresh fragrance combining sparkling citrus fruits with rare black tea and warm ambroxan.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 25,
    committed: 21,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Citron", "Calabrian Bergamot"],
    heart: ["Nigerian Ginger", "Ceylon Cinnamon"],
    base: ["Chinese Black Tea", "Ambroxan"],
  },
  {
    id: "f12",
    slug: "imperial-oud",
    name: "Imperial Oud",
    inspiration: "Inspired by Creed - Oud Zarian",
    tagline: "Saffron, Rose, Oud.",
    story: "Regal, sophisticated oriental woody blend pairing rich, smooth agarwood with warm spices and subtle leather.",
    price: 4700,
    price10: 2100,
    price30: 3400,
    gender: "unisex",
    moq: 30,
    committed: 18,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Saffron", "Nutmeg"],
    heart: ["Rose", "Labdanum"],
    base: ["Oud", "Leather", "Amber"],
  },
  {
    id: "f13",
    slug: "marine-absolute",
    name: "Marine Absolute",
    inspiration: "Inspired by Giorgio Armani - Acqua Di Gio Absolu",
    tagline: "Marine Notes, Rosemary, Patchouli.",
    story: "Powerful marine fragrance where fresh sea water meets warm, elegant woods and rich patchouli.",
    price: 4200,
    price10: 2000,
    price30: 3000,
    gender: "masculine",
    moq: 20,
    committed: 3,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Marine Notes", "Bergamot"],
    heart: ["Rosemary", "Lavender"],
    base: ["Patchouli", "Warm Woods"],
  },
  {
    id: "f14",
    slug: "wild-horizon",
    name: "Wild Horizon",
    inspiration: "Inspired by Dior - Sauvage EDP",
    tagline: "Calabria Bergamot, Sichuan Pepper, Ambroxan.",
    story: "Fiercely fresh, raw masculine composition balancing sharp bergamot with rich, smoky vanilla and heavy ambroxan.",
    price: 4000,
    price10: 1900,
    price30: 3000,
    gender: "masculine",
    moq: 22,
    committed: 2,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Calabria Bergamot"],
    heart: ["Sichuan Pepper", "Lavender"],
    base: ["Ambroxan", "Papua Vanilla"],
  },
  {
    id: "f15",
    slug: "imperial-vintage",
    name: "Imperial Vintage",
    inspiration: "Inspired by Creed - Aventus Absolu",
    tagline: "Grapefruit, Ginger, Patchouli.",
    story: "Sophisticated, darker evolution of a classic, blending rich, smoky dark woods with bright, juicy citrus top notes.",
    price: 4100,
    price10: 1900,
    price30: 3000,
    gender: "masculine",
    moq: 25,
    committed: 23,
    liquid: "#1f3a5e",
    accent: "#c9a961",
    top: ["Grapefruit", "Bergamot", "Blackcurrant"],
    heart: ["Ginger", "Cinnamon", "Cardamom"],
    base: ["Patchouli", "Vetiver"],
  },
  {
    id: "f16",
    slug: "neon-pulse",
    name: "Neon Pulse",
    inspiration: "Inspired by Jean Paul Gaultier - Ultra Male",
    tagline: "Pear, Cinnamon, Black Vanilla.",
    story: "Intensely sweet, high-impact masculine gourmand scent balancing spicy cinnamon with heavy black vanilla and juicy pear.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "masculine",
    moq: 30,
    committed: 15,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pear", "Lavender", "Mint"],
    heart: ["Cinnamon", "Clary Sage"],
    base: ["Black Vanilla", "Amber"],
  },
  {
    id: "f17",
    slug: "dark-caramel",
    name: "Dark Caramel",
    inspiration: "Inspired by Azzaro - Most Wanted",
    tagline: "Cardamom, Toffee, Amberwood.",
    story: "Ultra-addictive, rich fiery fragrance combining spicy cardamom with warm toffee and a deep woody trail.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "masculine",
    moq: 20,
    committed: 10,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Cardamom"],
    heart: ["Toffee"],
    base: ["Amberwood"],
  },
  {
    id: "f18",
    slug: "noble-woods",
    name: "Noble Woods",
    inspiration: "Inspired by Creed - Spice & Wood",
    tagline: "Apple, Angelica, Cedarwood.",
    story: "Incredibly refined, aristocratic blend of crisp green apple, sharp aromatic spices, and a clean, precious wood base.",
    price: 3800,
    price10: 1900,
    price30: 2800,
    gender: "unisex",
    moq: 22,
    committed: 7,
    liquid: "#9c4660",
    accent: "#e0b884",
    top: ["Apple", "Bergamot", "Lemon"],
    heart: ["Angelica", "Clove", "Pepper"],
    base: ["Cedarwood", "Birch", "Iris"],
  },
  {
    id: "f19",
    slug: "golden-elixir",
    name: "Golden Elixir",
    inspiration: "Inspired by Jean Paul Gaultier - Le Male Elixir",
    tagline: "Lavender, Vanilla, Honey.",
    story: "Rich, deeply aromatic oriental blend featuring intensely warm honeyed tobacco, clean lavender, and sweet tonka bean.",
    price: 3900,
    price10: 1900,
    price30: 2900,
    gender: "masculine",
    moq: 25,
    committed: 25,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Lavender", "Mint"],
    heart: ["Vanilla", "Benzoin"],
    base: ["Honey", "Tobacco", "Tonka Bean"],
  },
  {
    id: "f20",
    slug: "fierce-amber",
    name: "Fierce Amber",
    inspiration: "Inspired by Giorgio Armani - Stronger With You Intensely",
    tagline: "Pink Pepper, Toffee, Vanilla.",
    story: "Addictive, cozy oriental woody scent dominated by rich, sweet toffee notes, warm cinnamon, and deep amber.",
    price: 3800,
    price10: 1900,
    price30: 2800,
    gender: "masculine",
    moq: 30,
    committed: 12,
    liquid: "#5a3514",
    accent: "#d9b370",
    top: ["Pink Pepper", "Juniper"],
    heart: ["Toffee", "Cinnamon"],
    base: ["Vanilla", "Amber", "Suede"],
  },
  {
    id: "f21",
    slug: "smoked-suede",
    name: "Smoked Suede",
    inspiration: "Inspired by Tom Ford - Tuscan Leather",
    tagline: "Raspberry, Olibanum, Leather.",
    story: "Bold, ultra-luxurious lifestyle scent combining raw, heavy dark leather with sweet, bright wild raspberries.",
    price: 4000,
    price10: 1900,
    price30: 3000,
    gender: "unisex",
    moq: 20,
    committed: 17,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Raspberry", "Saffron"],
    heart: ["Olibanum", "Jasmine"],
    base: ["Leather", "Suede", "Amberwood"],
  },
  {
    id: "f22",
    slug: "dark-prestige",
    name: "Dark Prestige",
    inspiration: "Inspired by BOSS Bottle Absolu",
    tagline: "Leather Accord, Patchouli, Davana.",
    story: "Deeply intense, roasted woody-amber composition featuring rich leather accords, warm patchouli, and deep cedar.",
    price: 3600,
    price10: 1800,
    price30: 2700,
    gender: "masculine",
    moq: 22,
    committed: 12,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Leather Accord"],
    heart: ["Patchouli", "Cedarwood"],
    base: ["Davana", "Labdanum"],
  },
  {
    id: "f23",
    slug: "shadowed-oud",
    name: "Shadowed Oud",
    inspiration: "Inspired by Tom Ford - Oud Wood Intense",
    tagline: "Angelica Root, Oud (Agarwood), Castoreum.",
    story: "Rich, amplified woody fragrance delivering an earthy, primal take on traditional oud with sharp spices.",
    price: 4000,
    price10: 1900,
    price30: 2900,
    gender: "unisex",
    moq: 25,
    committed: 1,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Angelica Root", "Ginger"],
    heart: ["Oud (Agarwood)"],
    base: ["Castoreum", "Cypress"],
  },
  {
    id: "f24",
    slug: "celestial-fields",
    name: "Celestial Fields",
    inspiration: "Inspired by Roja - Elysium Eau",
    tagline: "Grapefruit, Lily-of-the-Valley, Ambergris.",
    story: "Brilliantly bright, sophisticated fresh fragrance bursting with crisp citrus, green apple, and clean, elegant musk.",
    price: 4200,
    price10: 2000,
    price30: 3100,
    gender: "masculine",
    moq: 30,
    committed: 9,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    top: ["Grapefruit", "Bergamot", "Lime"],
    heart: ["Lily-of-the-Valley", "Jasmine", "Apple"],
    base: ["Ambergris", "Musk", "Leather"],
  },
  {
    id: "f25",
    slug: "desert-nomad",
    name: "Desert Nomad",
    inspiration: "Inspired by Tom Ford - Ombre Nomade",
    tagline: "Raspberry, Saffron, Oud.",
    story: "Masterful, high-impact oriental fragrance combining deeply smoky oud wood with rich leather and sweet, dark raspberry.",
    price: 6300,
    price10: 2500,
    price30: 4400,
    gender: "unisex",
    moq: 20,
    committed: 3,
    liquid: "#2c1a0c",
    accent: "#c9a961",
    vipOnly: true,
    top: ["Raspberry"],
    heart: ["Saffron", "Rose"],
    base: ["Oud", "Leather", "Incense"],
  },
];

// ─── Design tokens ───────────────────────────────────────────────────────────
export const GOLD = "#c9a961";
export const CREAM = "#f3ecdc";
export const OBSIDIAN = "#0b0b0d";
export const HAIRLINE = "#1f1f27";

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Lighten (p > 0) or darken (p < 0) a #rrggbb hex toward white/black. */
export function shade(hex: string, p: number): string {
  const n = parseInt(hex.slice(1), 16);
  let r = (n >> 16) & 255;
  let g = (n >> 8) & 255;
  let b = n & 255;
  const t = p < 0 ? 0 : 255;
  const a = Math.abs(p);
  r = Math.round(r + (t - r) * a);
  g = Math.round(g + (t - g) * a);
  b = Math.round(b + (t - b) * a);
  return `rgb(${r},${g},${b})`;
}

export function money(cents: number): string {
  return "$" + Math.round(cents / 100);
}

export function pad(n: number): string {
  return String(n).padStart(2, "0");
}

export type Filter = "all" | "men" | "women";

export function matches(f: Fragrance, filter: Filter): boolean {
  if (filter === "all") return true;
  if (filter === "men") return f.gender === "masculine" || f.gender === "unisex";
  return f.gender === "feminine" || f.gender === "unisex";
}
